version: '3'
services:
  db:
    image: postgres:12.7-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '6969:5432'

volumes:
  postgres-data:
